### ISSUE TITLE
Price Plot labels out of order

### ISSUE THREAD

**Issue by warrenbyle** [JohannesByle/turbotin#33]
Looking at the plot for HH Rustica, I see that it lists them as blue - SmokingPipes, Red - CountrySquire, Orange - CupOJoes.  The plots are correct, but are referenced to the wrong store. The actual plots should be referenced as blue - CountrySquire, Red - CupOJoes, Orange - SmokingPipes.  So the labelling order appears to need to be rotated up one.

**Comment by JohannesByle** [comment]
I think I fixed it, I forgot to sort the list of store names. I think the columns in the pandas dataframe were already correctly sorted, but I made sure they were sorted as well.
