### ISSUE TITLE
FAQ modifications

### ISSUE THREAD

**Issue by warrenbyle** [JohannesByle/turbotin#41]
Just a placeholder to update the FAQ to reflect the new site changes.

Which online retailers are included in your search? - "From the Full Table, click the Filter Stores button to see a list of the current retailers in our search."

Is there different data on the hompage versus the Individual Blends page?  - probably delete this question

The main page is really long.  How do I find what I'm looking for? - probably delete this question

**Comment by JohannesByle** [comment]
The faq question are under turbotin/flask_app/static/[questions.json](https://github.com/JohannesByle/turbotin/blob/master/flask_app/static/questions.json) You can edit them directly from github.com, which is probably the easiest way to do it.
