### ISSUE TITLE
Can't select blends for notificaiton with appostrophe's in the title 

### ISSUE THREAD

**Issue by warrenbyle** [JohannesByle/turbotin#42]
I tried Bagpiper's Dream and Haddo's Delight and both can't be selected from the drop down.

**Comment by JohannesByle** [comment]
I switched the js function from taking the name of the blend/brand to taking the index so that there aren't any errors from the name not being html safe

**Comment by warrenbyle** [comment]
Awesome!  Glad it was an easy fix! Happy New Year from the Texas crew! -Warren Sent from Mail for Windows 10 From: Johannes ByleSent: Thursday, December 31, 2020 4:17 PMTo: JohannesByle/turbotinCc: warrenbyle; AuthorSubject: Re: [JohannesByle/turbotin] Can't select blends for notificaiton with appostrophe's in the title (#42) I switched the js function from taking the name of the blend/brand to taking the index so that there aren't any errors from the name not being html safe—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
