### ISSUE TITLE
Search Pane does not appear at 100 % zoom level

### ISSUE THREAD

**Issue by yakste** [JohannesByle/turbotin#53]
On laptop, the search pane on the left does not appear until zoomed out to 80 % or less, but by then on my laptop the text in the results box is getting hard to read. It took me a while to figure out why the search controls were missing.

Also, I could not find a link to your github repository on the new TurboTin site.

![TurboTin Desktop 100 Percent](https://github.com/JohannesByle/turbotin/assets/131413186/7013169e-c7a1-4c65-a344-169888c46fa5)

**Comment by yakste** [comment]
I'm unable to see the search tools on my Android phone, even in desktop mode and with landscape orientation. I tried Chrome and Duck Duck Go.

**Comment by JohannesByle** [comment]
Yeah, the mobile view is a bit of a WIP. I'll add that soon.
