### ISSUE TITLE
Internal Error, won't load any rows -> site down

### ISSUE THREAD

**Issue by yakste** [JohannesByle/turbotin#54]
I noticed this morning that TurboTin is throwing an internal error and won't load any rows, even with search and price history.

I went back to reference the site and the TurboTin site appears to be down now.

![image](https://github.com/JohannesByle/turbotin/assets/131413186/88efdf62-c0cb-4c7c-8eec-84c1295c6518)

**Comment by JohannesByle** [comment]
Thanks for letting me know. It's been fixed but I'll be looking into a long term solution.
