### ISSUE TITLE
No stock/price updates for over a month?

### ISSUE THREAD

**Issue by ctennison22** [JohannesByle/turbotin#56]
First off, thank you for creating/maintaining/fixing turbotin.  It's been a really helpful tool to help with my shopping.

Every blend on the site shows Last Updated to be "a month ago".  I watched it go from days to weeks and now over a month - like it's pulling no data at all.  I assumed the site was down and whoever was hosting it had given up.  But I see a ticket on here about the desktop search box not working that was created a week or so ago, so I guess some people are still using it.

Is there maybe an issue on my end, is there something I can do to get current pricing and stock?  Or is it actually down and not coming back up?

Thank you for your attention.

**Comment by JohannesByle** [comment]
Sorry, I had misconfigured something in the production environment. It's fixed now, thanks for letting me know.

**Comment by warrenbyle** [comment]
You probably have an old link from our prior hosting solution, so you will need to move to our new hosting site at turbotin.com.
________________________________
From: ctennison22 ***@***.***>
Sent: Friday, July 12, 2024 12:10 AM
To: JohannesByle/turbotin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JohannesByle/turbotin] No stock/price updates for over a month? (Issue #56)


First off, thank you for creating/maintaining/fixing turbotin. It's been a really helpful tool to help with my shopping.

Every blend on the site shows Last Updated to be "a month ago". I watched it go from days to weeks and now over a month - like it's pulling no data at all. I assumed the site was down and whoever was hosting it had given up. But I see a ticket on here about the desktop search box not working that was created a week or so ago, so I guess some people are still using it.

Is there maybe an issue on my end, is there something I can do to get current pricing and stock? Or is it actually down and not coming back up?

Thank you for your attention.

**Comment by ctennison22** [comment]
My God, I feel like an absolute fool. That’s one of the first things to check and I KNOW that, especially when the site has been making changes. Thank you and sorry I wasted your time.
